DANTE_CONST = {
	
	SERVICES : {
		ARC : '_netaudio-arc._udp.local', 
		CMC : '_netaudio-cmc._udp.local',
	},
	
	get SERVICES_ARRAY() { 
		return Object.values(DANTE_CONST.SERVICES);
	},
	
	AUDINATE_BUFFER : Buffer.concat([Buffer.from('Audinate', 'ascii'), Buffer.from('0734', 'hex')]),
	
	MULTICAST_IP : {
		INFO: '224.0.0.231',
		HEARTBEAT: '224.0.0.233',
	},
	
	PORTS : {
		ARC: 4440,
		SETTINGS: 8700,
		DVS_SETTINGS: 38700,
		INFO: 8702,
		HEARTBEAT: 8708,
		CMC: 8800,
		DVS_CMC: 38800
	},
	
	PROTOCOL : {
		//CONTROL: 0x27FF,
		CONTROL: 0x2729,
		SETTINGS: 0xFFFF,
		CMC: 0x1200,
		AES67_CONFIG: 0x2809,
		HEARTBEAT: 0xfffe,
	},
		
	COMMANDS : {
		channelCount : 0x1000,
		deviceInfo : 0x1003,
		deviceName : 0x1002,
		subscription : 0x3010,
		rxChannelNames : 0x3000,
		txChannelNames : 0x2010,
		txChannelInfo : 0x2000,
		setRxChannelName : 0x3001,
		setTxChannelName : 0x2013,
		setDeviceName : 0x1001,
		deviceSettings : 0x1100,
		setDeviceSettings : 0x1101,
		
		RESPONSE_DANTE_MODEL : 0x0060, //96,
		REQUEST_DANTE_MODEL : 0x0061, //97,
		RESPONSE_MAKE_MODEL : 0x00C0, //192,
		REQUEST_MAKE_MODEL : 0x00C1, //193,
		
		
		MESSAGE_TYPE_CHANNEL_COUNTS_QUERY : 0x1000, //4096,
		MESSAGE_TYPE_NAME_CONTROL : 0x1001, //4097,
		MESSAGE_TYPE_NAME_QUERY : 0x1002, //4098,
		MESSAGE_TYPE_DEVICE_CONTROL : 0x1003, //4099,
		MESSAGE_TYPE_IDENTIFY_DEVICE_QUERY : 0x10ce, //4302,
		MESSAGE_TYPE_DEVICE_SETTINGS_QUERY: 0x1100, 
		MESSAGE_TYPE_DEVICE_SETTINGS_CONTROL: 0x1101, 
		MESSAGE_TYPE_TX_CHANNEL_QUERY : 0x2000, //8192,
		MESSAGE_TYPE_TX_CHANNEL_FRIENDLY_NAMES_QUERY : 0x2010, //8208,
		MESSAGE_TYPE_TX_CHANNEL_NAMES_CONTROL : 0x2013,
		MESSAGE_TYPE_RX_CHANNEL_QUERY : 0x3000, //12288,
		MESSAGE_TYPE_RX_CHANNEL_CONTROL : 0x3001, //12289,
		
		
		MESSAGE_TYPE_ACCESS_CONTROL : 177,
		MESSAGE_TYPE_ACCESS_STATUS : 176,
		MESSAGE_TYPE_AES67_CONTROL : 4102,
		MESSAGE_TYPE_AES67_STATUS : 4103,
		MESSAGE_TYPE_AUDIO_INTERFACE_QUERY : 135,
		MESSAGE_TYPE_AUDIO_INTERFACE_STATUS : 134,
		MESSAGE_TYPE_CLEAR_CONFIG_CONTROL : 119,
		MESSAGE_TYPE_CLEAR_CONFIG_STATUS : 120,
		MESSAGE_TYPE_CLOCKING_CONTROL : 33,
		MESSAGE_TYPE_CLOCKING_STATUS : 32,
		MESSAGE_TYPE_CODEC_CONTROL : 0x100a, //4106,
		MESSAGE_TYPE_CODEC_STATUS : 0x100b, //4107,
		MESSAGE_TYPE_CONFIG_CONTROL : 115,
		MESSAGE_TYPE_DDM_ENROLMENT_CONFIG_CONTROL : 65286,
		MESSAGE_TYPE_DDM_ENROLMENT_CONFIG_STATUS : 65287,
		MESSAGE_TYPE_DEVICE_REBOOT : 146,
		MESSAGE_TYPE_EDK_BOARD_CONTROL : 161,
		MESSAGE_TYPE_EDK_BOARD_STATUS : 160,
		MESSAGE_TYPE_ENCODING_CONTROL : 0x0083, //131
		MESSAGE_TYPE_ENCODING_STATUS : 0x0082, //130
		MESSAGE_TYPE_HAREMOTE_CONTROL : 4097,
		MESSAGE_TYPE_HAREMOTE_STATUS : 4096,
		MESSAGE_TYPE_IDENTIFY_QUERY : 99,
		MESSAGE_TYPE_IDENTIFY_STATUS : 98,
		MESSAGE_TYPE_IFSTATS_QUERY : 65,
		MESSAGE_TYPE_IFSTATS_STATUS : 64,
		MESSAGE_TYPE_IGMP_VERS_CONTROL : 81,
		MESSAGE_TYPE_IGMP_VERS_STATUS : 80,
		MESSAGE_TYPE_INTERFACE_CONTROL : 19,
		MESSAGE_TYPE_INTERFACE_STATUS : 17,
		MESSAGE_TYPE_LED_QUERY : 209,
		MESSAGE_TYPE_LED_STATUS : 208,
		MESSAGE_TYPE_LOCK_QUERY : 4104,
		MESSAGE_TYPE_LOCK_STATUS : 4105,
		MESSAGE_TYPE_MANF_VERSIONS_QUERY : 0x00c1, //193,
		MESSAGE_TYPE_MANF_VERSIONS_STATUS : 0x00C0, //192,
		MESSAGE_TYPE_MASTER_QUERY : 35,
		MESSAGE_TYPE_MASTER_STATUS : 34,
		MESSAGE_TYPE_METERING_CONTROL : 225,
		MESSAGE_TYPE_METERING_STATUS : 224,
		MESSAGE_TYPE_NAME_ID_CONTROL : 39,
		MESSAGE_TYPE_NAME_ID_STATUS : 38,
		MESSAGE_TYPE_PROPERTY_CHANGE : 0x0106, //262,
		MESSAGE_TYPE_ROUTING_DEVICE_CHANGE : 0x0120, //288,
		MESSAGE_TYPE_ROUTING_READY : 0x0100, //256,
		MESSAGE_TYPE_RX_CHANNEL_CHANGE : 0x0102, //258,
		MESSAGE_TYPE_RX_CHANNEL_RX_ERROR_QUERY : 0x0111, //273,
		MESSAGE_TYPE_RX_CHANNEL_RX_ERROR_STATUS : 0x0110, //272,
		MESSAGE_TYPE_RX_ERROR_THRESHOLD_CONTROL : 0x0113, //275,
		MESSAGE_TYPE_RX_ERROR_THRESHOLD_STATUS : 0x0112, //274,
		MESSAGE_TYPE_RX_FLOW_CHANGE : 0x0105, //261,
		MESSAGE_TYPE_SAMPLE_RATE_CONTROL : 0x0081, //129,
		MESSAGE_TYPE_SAMPLE_RATE_STATUS : 0x0080, //128,
		MESSAGE_TYPE_SAMPLE_RATE_PULLUP_CONTROL : 0x0085, //133,
		MESSAGE_TYPE_SAMPLE_RATE_PULLUP_STATUS : 0x0084, //132,
		MESSAGE_TYPE_SERIAL_PORT_CONTROL : 241,
		MESSAGE_TYPE_SERIAL_PORT_STATUS : 240,
		MESSAGE_TYPE_SWITCH_VLAN_CONTROL : 21,
		MESSAGE_TYPE_SWITCH_VLAN_STATUS : 20,
		MESSAGE_TYPE_SYS_RESET : 144,
		MESSAGE_TYPE_TOPOLOGY_CHANGE : 16,
		MESSAGE_TYPE_TX_CHANNEL_CHANGE : 0x0101, //257,
		MESSAGE_TYPE_TX_FLOW_CHANGE : 0x0104, //260,
		MESSAGE_TYPE_TX_LABEL_CHANGE : 0x0103, //259,
		MESSAGE_TYPE_UNICAST_CLOCKING_CONTROL : 37,
		MESSAGE_TYPE_UNICAST_CLOCKING_STATUS : 36,
		MESSAGE_TYPE_UPGRADE_CONTROL : 113,
		MESSAGE_TYPE_UPGRADE_STATUS : 112,
		MESSAGE_TYPE_VERSIONS_QUERY : 97,
		MESSAGE_TYPE_VERSIONS_STATUS : 96,
	
	},

	
	ENCODINGS : {
		16: 'PCM16',
		24: 'PCM24',
		32: 'PCM32',
	},
	
	LEVELS : {
		1: '+18dBu',
		2: '+4dBu',
		3: '+0dBu',
		4:'0dBV',
		5: '-10dBV'
	},

	PULLUPS : {
		0: 'NONE',
		1: '+4,1667%',
		2: '+0.1%',
		3: '-0.1%',
		4: '-4%',
	},

	SUBSCRIPTION_STATUS : {
		NONE: 0,
		UNRESOLVED: 1,
		RESOLVED: 2,
		RESOLVE_FAIL: 3,
		SUBSCRIBE_SELF: 4,
		RESOLVED_NONE: 5,
		IDLE: 7,
		IN_PROGRESS: 8,
		DYNAMIC: 9,
		STATIC: 10,
		MANUAL: 14,
		NO_CONNECTION: 15,
		CHANNEL_FORMAT: 16,
		BUNDLE_FORMAT: 17,
		NO_RX: 18,
		RX_FAIL: 19,
		NO_TX: 20,
		TX_FAIL: 21,
		QOS_FAIL_RX: 22,
		QOS_FAIL_TX: 23,
		TX_REJECTED_ADDR: 24,
		INVALID_MSG: 25,
		CHANNEL_LATENCY: 26,
		CLOCK_DOMAIN: 27,
		UNSUPPORTED: 28,
		RX_LINK_DOWN: 29,
		TX_LINK_DOWN: 30,
		DYNAMIC_PROTOCOL: 31,
		INVALID_CHANNEL: 32,
		TX_SCHEDULER_FAILURE: 33,
		SUBSCRIBE_SELF_POLICY: 34,
		TX_NOT_READY: 35,
		RX_NOT_READY: 36,
		TX_FANOUT_LIMIT_REACHED: 37,
		TX_CHANNEL_ENCRYPTED: 38,
		TX_RESPONSE_UNEXPECTED: 39,
		TEMPLATE_MISMATCH_DEVICE: 64,
		TEMPLATE_MISMATCH_FORMAT: 65,
		TEMPLATE_MISSING_CHANNEL: 66,
		TEMPLATE_MISMATCH_CONFIG: 67,
		TEMPLATE_FULL: 68,
		RX_UNSUPPORTED_SUB_MODE: 69,
		TX_UNSUPPORTED_SUB_MODE: 70,
		TX_ACCESS_CONTROL_DENIED: 96,
		TX_ACCESS_CONTROL_PENDING: 97,
		HDCP_NEGOTIATION_ERROR: 112,
		RX_ENCRYPTION_UNSUPPORTED: 113,
		RX_TRANSPORT_UNSUPPORTED: 114,
		FLOW_DATA_STATUS_ERROR: 128,
		FLOW_DATA_STATUS_PENDING: 129,
		SYSTEM_FAIL: 255,
	},

	SUBSCRIPTION_STATUS_NAMES : {
		0: 'None',
		1: 'Unresolved',
		2: 'Resolved',
		3: 'Resolve Fail',
		4: 'Subscribe Self',
		5: 'Resolved None',
		7: 'Idle',
		8: 'In Progress',
		9: 'Connected (Unicast)',
		10: 'Connected (Multicast)',
		14: 'Manually Configured',
		15: 'No Connection',
		16: 'Channel Format Mismatch',
		17: 'Flow Format Mismatch',
		18: 'No Rx Flows',
		19: 'Rx Fail',
		20: 'No Tx Flows',
		21: 'Tx Fail',
		22: 'Rx Bandwidth Exceeded',
		23: 'Tx Bandwidth Exceeded',
		24: 'Tx Rejected Address',
		25: 'Invalid Message',
		26: 'Latency Mismatch',
		27: 'Clock Domain Mismatch',
		28: 'Unsupported',
		29: 'Rx Link Down',
		30: 'Tx Link Down',
		31: 'Dynamic Protocol',
		32: 'Invalid Channel',
		33: 'Tx Scheduler Failure',
		34: 'Subscribe Self Disallowed',
		35: 'Tx Not Ready',
		36: 'Rx Not Ready',
		37: 'Fanout Limit Reached (No Flows)',
		38: 'Tx Channel Encrypted',
		39: 'Tx Response Unexpected',
		64: 'Template Mismatch Device',
		65: 'Template Mismatch Format',
		66: 'Template Missing Channel',
		67: 'Template Mismatch Config',
		68: 'Template Full',
		69: 'Rx Unsupported Sub Mode',
		70: 'Tx Unsupported Sub Mode',
		96: 'Tx Access Control Denied',
		97: 'Tx Access Control Pending',
		112: 'HDCP Negotiation Error',
		113: 'Rx Encryption Unsupported',
		114: 'Rx Transport Unsupported',
		128: 'Flow Data Status Error',
		129: 'Flow Data Status Pending',
		255: 'System Failure',
	},
};

const object2choices = (obj) => {
	let choices = [];
	for (const [id, label] of Object.entries(obj)) {
		choices.push({id: id, label: label})
	};
	return choices;
};

const object2PartialChoices = (obj, optionsArray) => {
	let choices = [];
	for (const [id, label] of Object.entries(obj)) { 
		if (optionsArray?.includes(id)) {
			choices.push({id: id, label: label})
		}
	};
	return choices;
};

const array2choices = (array, mapping) => {
	const choices = array?.map((e) => {
		return {id: e, label: mapping ? mapping(e) : e};
	});
	return choices;
};

module.exports = {DANTE_CONST, object2choices, object2PartialChoices, array2choices};
